#!/usr/bin/env bash
# Naive Chapter Splitter:
# Splits on lines ending with
# a number and a trailing period

if [[ "$1" = "" ]]; then
    echo "usage: $(basename "$0") <file>"
    exit
fi

csplit --elide-empty-files "$1" "/[0-9]\.$/" "{*}"

exit $?
