#!/usr/bin/env bash
# split on lines containing
# only numbers w/ trailing period

if [[ "$1" = "" ]]; then
    echo "usage: $(basename "$0") <file>"
    exit
fi

csplit --elide-empty-files "$1" "/[0-9]\.$/" "{*}"

exit $?
